
server :
     port : 8083
eureka:
   client:
        serviceUrl:
                  defaultZone  : http://localhost:8761/eureka
        instance:
                preferIpAddress : true
management:
          tracing:
                  sampling:
                          probability : 1.0
spring:
      application:
                 name : api-gateway
      cloud:
           gateway:
                  routes:
                      - id: employee-service
                        uri: lb://employee-service
                        predicates:
                          - Path=/employee/**
                      - id: departement-service
                        uri: lb://departement-service
                        predicates:
                          - Path=/department/**

      config:
        import: "optional:configserver:http://localhost:8088"



